apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cache-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-cache
  template:
    metadata:
      labels:
        name: flask-cache
    spec:
      containers:
        - name: cache-service
          image: xasag94215/flask-cache
          ports:
            - containerPort: 5000
              name: rest
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cache-service
spec:
  selector:
    name: flask-cache
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-cache-ingress
spec:
  defaultBackend:
    service:
      name: flask-cache
      port:
        number: 80
#  rules:
#    - http:
#        paths:
#          - backend:
#              service:
#                name: flask-cache
#                port:
#                  number: 80
#            path: /
#            pathType: Prefix
