apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-ap-dp
  name: spring-boot-ap-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-ap-dp
  template:
    metadata:
      labels:
        app: spring-boot-ap-dp
    spec:
      containers:
        - image: spring-boot-ap:latest
          name: spring-boot-ap
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
